version: '3'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: appfactory-nginx
    container_name: app-nginx
    networks:
      static-network:
        ipv4_address: 172.20.0.2
    ports:
      - 80:80
#      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs
      - $APPFACTORY_VOLUME_PATH/logs:/usr/volumes/logs
    command: [nginx-debug, '-g', 'daemon off;']

  db:
    build:
      context: postgres
      dockerfile: Dockerfile-10.9
    image: appfactory-pg:10.9
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PSWD}
      POSTGRES_PSWD: ${POSTGRES_PSWD}
      POSTGRES_OWNER_PSWD: ${POSTGRES_OWNER_PSWD}
    networks:
      static-network:
        ipv4_address: 172.20.0.3
    ports:
      - 5433:5432
    volumes:
      - $APPFACTORY_VOLUME_PATH/postgres/data:/var/lib/postgresql/data

  server:
    build:
      context: server
      dockerfile: Dockerfile
    image: appfactory-server
    container_name: appserver
    environment:
      POSTGRES_HOST:          postgres
      POSTGRES_PORT:          5432
      POSTGRES_NAME:          ${POSTGRES_NAME}
      POSTGRES_USER:          ${POSTGRES_USER}
      POSTGRES_PASSWORD:      ${POSTGRES_PSWD}
      POSTGRES_PSWD:          ${POSTGRES_PSWD}
      POSTGRES_OWNER_PSWD:    ${POSTGRES_OWNER_PSWD}
      APPFACTORY_VOLUME_PATH: /usr/volumes
      VUE_APP_EMAIL:          ${VUE_APP_EMAIL}
      VUE_APP_PSWD:           ${VUE_APP_PSWD}
      REST_APP_MODE:          ${REST_APP_MODE}
      REST_APP_USERID:        ${REST_APP_USERID}
      VUE_APP_MODE:           ${VUE_APP_MODE}
      VUE_APP_LEVEL:          ${VUE_APP_LEVEL}
    networks:
      static-network:
        ipv4_address: 172.20.0.4
    ports:
      - 3000:3000
    volumes:
      - $APPFACTORY_SOURCE_PATH/services:/usr/src/app
      - $APPFACTORY_VOLUME_PATH:/usr/volumes

  web:
    build:
      context: web
      dockerfile: Dockerfile
    image: appfactory-web
    container_name: web
    environment:
      VUE_APP_EMAIL:          ${VUE_APP_EMAIL}
      VUE_APP_PSWD:           ${VUE_APP_PSWD}
      VUE_APP_MODE:           ${VUE_APP_MODE}
      VUE_APP_LEVEL:          ${VUE_APP_LEVEL}
      VUE_APP_REST_HOST:      www.appfactory.com/api
      VUE_APP_REST_PORT:
    networks:
      static-network:
        ipv4_address: 172.20.0.5
    ports:
      - 8080:8080
    volumes:
      - $APPFACTORY_SOURCE_PATH/appfactory:/usr/src/web

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
