version: '3.7'

services:
  swagger-ui:
    build:
      context: ui
      dockerfile: Dockerfile
    image: swagger-ui
    container_name: swagger-ui
    ports:
      - 8000:8080

  swagger-editor:
    build:
      context: editor
      dockerfile: Dockerfile
    image: swagger-editor
    container_name: swagger-editor
    ports:
      - 81:8080

#  server:
#    build:
#      context: server
#      dockerfile: Dockerfile
#    image: appfactory-server
#    container_name: appserver
#    environment:
#      NODE_ENV:               development
#      POSTGRES_HOST:          postgres
#      POSTGRES_PORT:          5432
#      POSTGRES_NAME:          ${POSTGRES_NAME}
#      POSTGRES_USER:          ${POSTGRES_USER}
#      POSTGRES_PASSWORD:      ${POSTGRES_PSWD}
#      POSTGRES_PSWD:          ${POSTGRES_PSWD}
#      POSTGRES_OWNER_PSWD:    ${POSTGRES_OWNER_PSWD}
#      APPFACTORY_VOLUME_PATH: /usr/volumes
#      VUE_APP_EMAIL:          ${VUE_APP_EMAIL}
#      VUE_APP_PSWD:           ${VUE_APP_PSWD}
#      VUE_APP_MODE:           ${VUE_APP_MODE}
#      VUE_APP_LEVEL:          ${VUE_APP_LEVEL}
#      VUE_APP_PROTOCOL:       http
#      VUE_APP_REST_HOST:      www.appfactory.com
#      VUE_APP_REST_PORT:      3000
#    networks:
#      static-network:
#        ipv4_address: 172.20.0.4
#    ports:
#      - 3000:3000
#    volumes:
#      - $APPFACTORY_SOURCE_PATH/services:/usr/src/app
#      - $APPFACTORY_VOLUME_PATH:/usr/volumes
