version: '3'

services:
  app1:
    build: application
    image: load-balanced-app
    environment:
      MESSAGE: 'First Instance'
    ports:
      - 8081:8080
  app2:
    build: application
    image: load-balanced-app
    environment:
      MESSAGE: 'Second Instance'
    ports:
      - 8082:8080
  nginx:
    build: .
    image: load-balance-nginx
    ports:
      - 8080:80

