version: '3'

services:
  app1:
    build: application
    image: localhost:5000/load-balanced-app
    container_name: app1
    environment:
      MESSAGE: 'First Instance'
    networks:
      static-network:
        ipv4_address: 172.20.0.2
    ports:
      - 8081:8080
  app2:
    build: application
    image: localhost:5000/load-balanced-app
    container_name: app2
    environment:
      MESSAGE: 'Second Instance'
    networks:
      static-network:
        ipv4_address: 172.20.0.3
    ports:
      - 8082:8080
  nginx:
    build: .
    image: localhost:5000/load-balance-nginx-test
    container_name: nginx-test
    networks:
      static-network:
        ipv4_address: 172.20.0.4
    ports:
      - 8080:80

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
